// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(zeromax_ffiFFI)
import zeromax_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_zeromax_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_zeromax_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol ZeroMaxClientProtocol : AnyObject {
    
    func addReaction(chatId: Int64, messageId: String, reaction: String) throws  -> FfiReactionInfo?
    
    func changeProfile(firstName: String, lastName: String?, description: String?) throws 
    
    func check2faPassword(trackId: String, password: String) throws  -> String?
    
    func completeQrLogin(trackId: String) throws  -> String
    
    func connect() throws 
    
    func connectForAuth() throws 
    
    func deleteMessage(chatId: Int64, messageIds: [Int64], forMe: Bool) throws 
    
    func editMessage(chatId: Int64, messageId: Int64, text: String) throws  -> FfiMessage
    
    func fetchHistory(chatId: Int64, fromTime: Int64?, count: Int32) throws  -> [FfiMessage]
    
    func getChatList()  -> [FfiChatItem]
    
    func getMe()  -> FfiMe?
    
    func getUser(userId: Int64) throws  -> FfiUser
    
    func isConnected()  -> Bool
    
    func joinChat(link: String) throws 
    
    func leaveChat(chatId: Int64) throws 
    
    func loadAllChats() throws 
    
    func loginWithCode(tempToken: String, code: String) throws 
    
    func pollQrStatus(trackId: String) throws  -> Bool
    
    func readMessage(chatId: Int64, messageId: Int64) throws 
    
    func removeReaction(chatId: Int64, messageId: String) throws  -> FfiReactionInfo?
    
    func requestCode(phone: String, language: String) throws  -> String
    
    func requestQr() throws  -> FfiQrLoginData
    
    func resolveDialogUsers() throws 
    
    func sendMessage(chatId: Int64, text: String, replyTo: Int64?) throws  -> FfiMessage
    
    func sendTyping(chatId: Int64) throws 
    
    func serverLogout() throws 
    
    func setEventListener(listener: EventListener) 
    
    func setToken(token: String) throws 
    
    func startBackgroundReconnect() 
    
    func startEventLoop() 
    
    func syncAfterLogin() throws 
    
    func verifyCode(code: String, tempToken: String) throws  -> FfiCodeResult
    
}

open class ZeroMaxClient:
    ZeroMaxClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_zeromax_ffi_fn_clone_zeromaxclient(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_zeromax_ffi_fn_free_zeromaxclient(pointer, $0) }
    }

    
public static func newClient(config: FfiClientConfig)throws  -> ZeroMaxClient {
    return try  FfiConverterTypeZeroMaxClient.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_constructor_zeromaxclient_new_client(
        FfiConverterTypeFfiClientConfig.lower(config),$0
    )
})
}
    

    
open func addReaction(chatId: Int64, messageId: String, reaction: String)throws  -> FfiReactionInfo? {
    return try  FfiConverterOptionTypeFfiReactionInfo.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_add_reaction(self.uniffiClonePointer(),
        FfiConverterInt64.lower(chatId),
        FfiConverterString.lower(messageId),
        FfiConverterString.lower(reaction),$0
    )
})
}
    
open func changeProfile(firstName: String, lastName: String?, description: String?)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_change_profile(self.uniffiClonePointer(),
        FfiConverterString.lower(firstName),
        FfiConverterOptionString.lower(lastName),
        FfiConverterOptionString.lower(description),$0
    )
}
}
    
open func check2faPassword(trackId: String, password: String)throws  -> String? {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_check_2fa_password(self.uniffiClonePointer(),
        FfiConverterString.lower(trackId),
        FfiConverterString.lower(password),$0
    )
})
}
    
open func completeQrLogin(trackId: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_complete_qr_login(self.uniffiClonePointer(),
        FfiConverterString.lower(trackId),$0
    )
})
}
    
open func connect()throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_connect(self.uniffiClonePointer(),$0
    )
}
}
    
open func connectForAuth()throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_connect_for_auth(self.uniffiClonePointer(),$0
    )
}
}
    
open func deleteMessage(chatId: Int64, messageIds: [Int64], forMe: Bool)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_delete_message(self.uniffiClonePointer(),
        FfiConverterInt64.lower(chatId),
        FfiConverterSequenceInt64.lower(messageIds),
        FfiConverterBool.lower(forMe),$0
    )
}
}
    
open func editMessage(chatId: Int64, messageId: Int64, text: String)throws  -> FfiMessage {
    return try  FfiConverterTypeFfiMessage.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_edit_message(self.uniffiClonePointer(),
        FfiConverterInt64.lower(chatId),
        FfiConverterInt64.lower(messageId),
        FfiConverterString.lower(text),$0
    )
})
}
    
open func fetchHistory(chatId: Int64, fromTime: Int64?, count: Int32)throws  -> [FfiMessage] {
    return try  FfiConverterSequenceTypeFfiMessage.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_fetch_history(self.uniffiClonePointer(),
        FfiConverterInt64.lower(chatId),
        FfiConverterOptionInt64.lower(fromTime),
        FfiConverterInt32.lower(count),$0
    )
})
}
    
open func getChatList() -> [FfiChatItem] {
    return try!  FfiConverterSequenceTypeFfiChatItem.lift(try! rustCall() {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_get_chat_list(self.uniffiClonePointer(),$0
    )
})
}
    
open func getMe() -> FfiMe? {
    return try!  FfiConverterOptionTypeFfiMe.lift(try! rustCall() {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_get_me(self.uniffiClonePointer(),$0
    )
})
}
    
open func getUser(userId: Int64)throws  -> FfiUser {
    return try  FfiConverterTypeFfiUser.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_get_user(self.uniffiClonePointer(),
        FfiConverterInt64.lower(userId),$0
    )
})
}
    
open func isConnected() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_is_connected(self.uniffiClonePointer(),$0
    )
})
}
    
open func joinChat(link: String)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_join_chat(self.uniffiClonePointer(),
        FfiConverterString.lower(link),$0
    )
}
}
    
open func leaveChat(chatId: Int64)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_leave_chat(self.uniffiClonePointer(),
        FfiConverterInt64.lower(chatId),$0
    )
}
}
    
open func loadAllChats()throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_load_all_chats(self.uniffiClonePointer(),$0
    )
}
}
    
open func loginWithCode(tempToken: String, code: String)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_login_with_code(self.uniffiClonePointer(),
        FfiConverterString.lower(tempToken),
        FfiConverterString.lower(code),$0
    )
}
}
    
open func pollQrStatus(trackId: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_poll_qr_status(self.uniffiClonePointer(),
        FfiConverterString.lower(trackId),$0
    )
})
}
    
open func readMessage(chatId: Int64, messageId: Int64)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_read_message(self.uniffiClonePointer(),
        FfiConverterInt64.lower(chatId),
        FfiConverterInt64.lower(messageId),$0
    )
}
}
    
open func removeReaction(chatId: Int64, messageId: String)throws  -> FfiReactionInfo? {
    return try  FfiConverterOptionTypeFfiReactionInfo.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_remove_reaction(self.uniffiClonePointer(),
        FfiConverterInt64.lower(chatId),
        FfiConverterString.lower(messageId),$0
    )
})
}
    
open func requestCode(phone: String, language: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_request_code(self.uniffiClonePointer(),
        FfiConverterString.lower(phone),
        FfiConverterString.lower(language),$0
    )
})
}
    
open func requestQr()throws  -> FfiQrLoginData {
    return try  FfiConverterTypeFfiQrLoginData.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_request_qr(self.uniffiClonePointer(),$0
    )
})
}
    
open func resolveDialogUsers()throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_resolve_dialog_users(self.uniffiClonePointer(),$0
    )
}
}
    
open func sendMessage(chatId: Int64, text: String, replyTo: Int64?)throws  -> FfiMessage {
    return try  FfiConverterTypeFfiMessage.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_send_message(self.uniffiClonePointer(),
        FfiConverterInt64.lower(chatId),
        FfiConverterString.lower(text),
        FfiConverterOptionInt64.lower(replyTo),$0
    )
})
}
    
open func sendTyping(chatId: Int64)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_send_typing(self.uniffiClonePointer(),
        FfiConverterInt64.lower(chatId),$0
    )
}
}
    
open func serverLogout()throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_server_logout(self.uniffiClonePointer(),$0
    )
}
}
    
open func setEventListener(listener: EventListener) {try! rustCall() {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_set_event_listener(self.uniffiClonePointer(),
        FfiConverterCallbackInterfaceEventListener.lower(listener),$0
    )
}
}
    
open func setToken(token: String)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_set_token(self.uniffiClonePointer(),
        FfiConverterString.lower(token),$0
    )
}
}
    
open func startBackgroundReconnect() {try! rustCall() {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_start_background_reconnect(self.uniffiClonePointer(),$0
    )
}
}
    
open func startEventLoop() {try! rustCall() {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_start_event_loop(self.uniffiClonePointer(),$0
    )
}
}
    
open func syncAfterLogin()throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_sync_after_login(self.uniffiClonePointer(),$0
    )
}
}
    
open func verifyCode(code: String, tempToken: String)throws  -> FfiCodeResult {
    return try  FfiConverterTypeFfiCodeResult.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeromax_ffi_fn_method_zeromaxclient_verify_code(self.uniffiClonePointer(),
        FfiConverterString.lower(code),
        FfiConverterString.lower(tempToken),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZeroMaxClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ZeroMaxClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ZeroMaxClient {
        return ZeroMaxClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ZeroMaxClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZeroMaxClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ZeroMaxClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZeroMaxClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> ZeroMaxClient {
    return try FfiConverterTypeZeroMaxClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZeroMaxClient_lower(_ value: ZeroMaxClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeZeroMaxClient.lower(value)
}


public struct FfiChatItem {
    public var id: Int64
    public var chatType: FfiChatType
    public var title: String
    public var lastMessageText: String
    public var lastMessageTime: Int64
    public var avatarUrl: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64, chatType: FfiChatType, title: String, lastMessageText: String, lastMessageTime: Int64, avatarUrl: String?) {
        self.id = id
        self.chatType = chatType
        self.title = title
        self.lastMessageText = lastMessageText
        self.lastMessageTime = lastMessageTime
        self.avatarUrl = avatarUrl
    }
}



extension FfiChatItem: Equatable, Hashable {
    public static func ==(lhs: FfiChatItem, rhs: FfiChatItem) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.chatType != rhs.chatType {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.lastMessageText != rhs.lastMessageText {
            return false
        }
        if lhs.lastMessageTime != rhs.lastMessageTime {
            return false
        }
        if lhs.avatarUrl != rhs.avatarUrl {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(chatType)
        hasher.combine(title)
        hasher.combine(lastMessageText)
        hasher.combine(lastMessageTime)
        hasher.combine(avatarUrl)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiChatItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiChatItem {
        return
            try FfiChatItem(
                id: FfiConverterInt64.read(from: &buf), 
                chatType: FfiConverterTypeFfiChatType.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                lastMessageText: FfiConverterString.read(from: &buf), 
                lastMessageTime: FfiConverterInt64.read(from: &buf), 
                avatarUrl: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiChatItem, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterTypeFfiChatType.write(value.chatType, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.lastMessageText, into: &buf)
        FfiConverterInt64.write(value.lastMessageTime, into: &buf)
        FfiConverterOptionString.write(value.avatarUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiChatItem_lift(_ buf: RustBuffer) throws -> FfiChatItem {
    return try FfiConverterTypeFfiChatItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiChatItem_lower(_ value: FfiChatItem) -> RustBuffer {
    return FfiConverterTypeFfiChatItem.lower(value)
}


public struct FfiClientConfig {
    public var phone: String
    public var workDir: String
    public var token: String?
    public var deviceType: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(phone: String, workDir: String, token: String?, deviceType: String?) {
        self.phone = phone
        self.workDir = workDir
        self.token = token
        self.deviceType = deviceType
    }
}



extension FfiClientConfig: Equatable, Hashable {
    public static func ==(lhs: FfiClientConfig, rhs: FfiClientConfig) -> Bool {
        if lhs.phone != rhs.phone {
            return false
        }
        if lhs.workDir != rhs.workDir {
            return false
        }
        if lhs.token != rhs.token {
            return false
        }
        if lhs.deviceType != rhs.deviceType {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(phone)
        hasher.combine(workDir)
        hasher.combine(token)
        hasher.combine(deviceType)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiClientConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiClientConfig {
        return
            try FfiClientConfig(
                phone: FfiConverterString.read(from: &buf), 
                workDir: FfiConverterString.read(from: &buf), 
                token: FfiConverterOptionString.read(from: &buf), 
                deviceType: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiClientConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.phone, into: &buf)
        FfiConverterString.write(value.workDir, into: &buf)
        FfiConverterOptionString.write(value.token, into: &buf)
        FfiConverterOptionString.write(value.deviceType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClientConfig_lift(_ buf: RustBuffer) throws -> FfiClientConfig {
    return try FfiConverterTypeFfiClientConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClientConfig_lower(_ value: FfiClientConfig) -> RustBuffer {
    return FfiConverterTypeFfiClientConfig.lower(value)
}


public struct FfiMe {
    public var id: Int64
    public var phone: String
    public var displayName: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64, phone: String, displayName: String) {
        self.id = id
        self.phone = phone
        self.displayName = displayName
    }
}



extension FfiMe: Equatable, Hashable {
    public static func ==(lhs: FfiMe, rhs: FfiMe) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.phone != rhs.phone {
            return false
        }
        if lhs.displayName != rhs.displayName {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(phone)
        hasher.combine(displayName)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiMe: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMe {
        return
            try FfiMe(
                id: FfiConverterInt64.read(from: &buf), 
                phone: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMe, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.phone, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMe_lift(_ buf: RustBuffer) throws -> FfiMe {
    return try FfiConverterTypeFfiMe.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMe_lower(_ value: FfiMe) -> RustBuffer {
    return FfiConverterTypeFfiMe.lower(value)
}


public struct FfiMessage {
    public var id: Int64
    public var chatId: Int64
    public var time: Int64
    public var text: String
    public var senderId: Int64
    public var senderName: String
    public var isOutgoing: Bool
    public var status: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64, chatId: Int64, time: Int64, text: String, senderId: Int64, senderName: String, isOutgoing: Bool, status: String?) {
        self.id = id
        self.chatId = chatId
        self.time = time
        self.text = text
        self.senderId = senderId
        self.senderName = senderName
        self.isOutgoing = isOutgoing
        self.status = status
    }
}



extension FfiMessage: Equatable, Hashable {
    public static func ==(lhs: FfiMessage, rhs: FfiMessage) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.chatId != rhs.chatId {
            return false
        }
        if lhs.time != rhs.time {
            return false
        }
        if lhs.text != rhs.text {
            return false
        }
        if lhs.senderId != rhs.senderId {
            return false
        }
        if lhs.senderName != rhs.senderName {
            return false
        }
        if lhs.isOutgoing != rhs.isOutgoing {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(chatId)
        hasher.combine(time)
        hasher.combine(text)
        hasher.combine(senderId)
        hasher.combine(senderName)
        hasher.combine(isOutgoing)
        hasher.combine(status)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMessage {
        return
            try FfiMessage(
                id: FfiConverterInt64.read(from: &buf), 
                chatId: FfiConverterInt64.read(from: &buf), 
                time: FfiConverterInt64.read(from: &buf), 
                text: FfiConverterString.read(from: &buf), 
                senderId: FfiConverterInt64.read(from: &buf), 
                senderName: FfiConverterString.read(from: &buf), 
                isOutgoing: FfiConverterBool.read(from: &buf), 
                status: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMessage, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterInt64.write(value.chatId, into: &buf)
        FfiConverterInt64.write(value.time, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterInt64.write(value.senderId, into: &buf)
        FfiConverterString.write(value.senderName, into: &buf)
        FfiConverterBool.write(value.isOutgoing, into: &buf)
        FfiConverterOptionString.write(value.status, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMessage_lift(_ buf: RustBuffer) throws -> FfiMessage {
    return try FfiConverterTypeFfiMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMessage_lower(_ value: FfiMessage) -> RustBuffer {
    return FfiConverterTypeFfiMessage.lower(value)
}


public struct FfiQrLoginData {
    public var qrLink: String
    public var trackId: String
    public var pollingIntervalMs: UInt64
    public var expiresAtMs: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(qrLink: String, trackId: String, pollingIntervalMs: UInt64, expiresAtMs: Int64) {
        self.qrLink = qrLink
        self.trackId = trackId
        self.pollingIntervalMs = pollingIntervalMs
        self.expiresAtMs = expiresAtMs
    }
}



extension FfiQrLoginData: Equatable, Hashable {
    public static func ==(lhs: FfiQrLoginData, rhs: FfiQrLoginData) -> Bool {
        if lhs.qrLink != rhs.qrLink {
            return false
        }
        if lhs.trackId != rhs.trackId {
            return false
        }
        if lhs.pollingIntervalMs != rhs.pollingIntervalMs {
            return false
        }
        if lhs.expiresAtMs != rhs.expiresAtMs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(qrLink)
        hasher.combine(trackId)
        hasher.combine(pollingIntervalMs)
        hasher.combine(expiresAtMs)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiQrLoginData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiQrLoginData {
        return
            try FfiQrLoginData(
                qrLink: FfiConverterString.read(from: &buf), 
                trackId: FfiConverterString.read(from: &buf), 
                pollingIntervalMs: FfiConverterUInt64.read(from: &buf), 
                expiresAtMs: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiQrLoginData, into buf: inout [UInt8]) {
        FfiConverterString.write(value.qrLink, into: &buf)
        FfiConverterString.write(value.trackId, into: &buf)
        FfiConverterUInt64.write(value.pollingIntervalMs, into: &buf)
        FfiConverterInt64.write(value.expiresAtMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiQrLoginData_lift(_ buf: RustBuffer) throws -> FfiQrLoginData {
    return try FfiConverterTypeFfiQrLoginData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiQrLoginData_lower(_ value: FfiQrLoginData) -> RustBuffer {
    return FfiConverterTypeFfiQrLoginData.lower(value)
}


public struct FfiReactionInfo {
    public var totalCount: Int32
    public var yourReaction: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(totalCount: Int32, yourReaction: String?) {
        self.totalCount = totalCount
        self.yourReaction = yourReaction
    }
}



extension FfiReactionInfo: Equatable, Hashable {
    public static func ==(lhs: FfiReactionInfo, rhs: FfiReactionInfo) -> Bool {
        if lhs.totalCount != rhs.totalCount {
            return false
        }
        if lhs.yourReaction != rhs.yourReaction {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(totalCount)
        hasher.combine(yourReaction)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiReactionInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiReactionInfo {
        return
            try FfiReactionInfo(
                totalCount: FfiConverterInt32.read(from: &buf), 
                yourReaction: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiReactionInfo, into buf: inout [UInt8]) {
        FfiConverterInt32.write(value.totalCount, into: &buf)
        FfiConverterOptionString.write(value.yourReaction, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiReactionInfo_lift(_ buf: RustBuffer) throws -> FfiReactionInfo {
    return try FfiConverterTypeFfiReactionInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiReactionInfo_lower(_ value: FfiReactionInfo) -> RustBuffer {
    return FfiConverterTypeFfiReactionInfo.lower(value)
}


public struct FfiUser {
    public var id: Int64
    public var displayName: String
    public var avatarUrl: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64, displayName: String, avatarUrl: String?) {
        self.id = id
        self.displayName = displayName
        self.avatarUrl = avatarUrl
    }
}



extension FfiUser: Equatable, Hashable {
    public static func ==(lhs: FfiUser, rhs: FfiUser) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.displayName != rhs.displayName {
            return false
        }
        if lhs.avatarUrl != rhs.avatarUrl {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(displayName)
        hasher.combine(avatarUrl)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiUser: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiUser {
        return
            try FfiUser(
                id: FfiConverterInt64.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf), 
                avatarUrl: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiUser, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterOptionString.write(value.avatarUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiUser_lift(_ buf: RustBuffer) throws -> FfiUser {
    return try FfiConverterTypeFfiUser.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiUser_lower(_ value: FfiUser) -> RustBuffer {
    return FfiConverterTypeFfiUser.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiChatType {
    
    case dialog
    case chat
    case channel
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiChatType: FfiConverterRustBuffer {
    typealias SwiftType = FfiChatType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiChatType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .dialog
        
        case 2: return .chat
        
        case 3: return .channel
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiChatType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .dialog:
            writeInt(&buf, Int32(1))
        
        
        case .chat:
            writeInt(&buf, Int32(2))
        
        
        case .channel:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiChatType_lift(_ buf: RustBuffer) throws -> FfiChatType {
    return try FfiConverterTypeFfiChatType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiChatType_lower(_ value: FfiChatType) -> RustBuffer {
    return FfiConverterTypeFfiChatType.lower(value)
}



extension FfiChatType: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiCodeResult {
    
    case loggedIn(token: String
    )
    case twoFactorRequired(trackId: String, hint: String?
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiCodeResult: FfiConverterRustBuffer {
    typealias SwiftType = FfiCodeResult

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCodeResult {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .loggedIn(token: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .twoFactorRequired(trackId: try FfiConverterString.read(from: &buf), hint: try FfiConverterOptionString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiCodeResult, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .loggedIn(token):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(token, into: &buf)
            
        
        case let .twoFactorRequired(trackId,hint):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(trackId, into: &buf)
            FfiConverterOptionString.write(hint, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCodeResult_lift(_ buf: RustBuffer) throws -> FfiCodeResult {
    return try FfiConverterTypeFfiCodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCodeResult_lower(_ value: FfiCodeResult) -> RustBuffer {
    return FfiConverterTypeFfiCodeResult.lower(value)
}



extension FfiCodeResult: Equatable, Hashable {}




public enum FfiError {

    
    
    case Auth(message: String)
    
    case NotConnected(message: String)
    
    case Timeout(message: String)
    
    case InvalidPhone(message: String)
    
    case Server(message: String)
    
    case Network(message: String)
    
    case Internal(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Auth(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .NotConnected(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Timeout(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .InvalidPhone(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .Server(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .Network(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .Internal(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Auth(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .NotConnected(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Timeout(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .InvalidPhone(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .Server(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .Network(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .Internal(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))

        
        }
    }
}


extension FfiError: Equatable, Hashable {}

extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




public protocol EventListener : AnyObject {
    
    func onNewMessage(message: FfiMessage) 
    
    func onMessageEdited(message: FfiMessage) 
    
    func onMessageDeleted(message: FfiMessage) 
    
    func onChatUpdated(chat: FfiChatItem) 
    
    func onTyping(chatId: Int64, userId: Int64) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceEventListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceEventListener = UniffiVTableCallbackInterfaceEventListener(
        onNewMessage: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onNewMessage(
                     message: try FfiConverterTypeFfiMessage.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onMessageEdited: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onMessageEdited(
                     message: try FfiConverterTypeFfiMessage.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onMessageDeleted: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onMessageDeleted(
                     message: try FfiConverterTypeFfiMessage.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onChatUpdated: { (
            uniffiHandle: UInt64,
            chat: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onChatUpdated(
                     chat: try FfiConverterTypeFfiChatItem.lift(chat)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onTyping: { (
            uniffiHandle: UInt64,
            chatId: Int64,
            userId: Int64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onTyping(
                     chatId: try FfiConverterInt64.lift(chatId),
                     userId: try FfiConverterInt64.lift(userId)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceEventListener.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface EventListener: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitEventListener() {
    uniffi_zeromax_ffi_fn_init_callback_vtable_eventlistener(&UniffiCallbackInterfaceEventListener.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceEventListener {
    fileprivate static var handleMap = UniffiHandleMap<EventListener>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceEventListener : FfiConverter {
    typealias SwiftType = EventListener
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiMe: FfiConverterRustBuffer {
    typealias SwiftType = FfiMe?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiMe.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiMe.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiReactionInfo: FfiConverterRustBuffer {
    typealias SwiftType = FfiReactionInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiReactionInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiReactionInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceInt64: FfiConverterRustBuffer {
    typealias SwiftType = [Int64]

    public static func write(_ value: [Int64], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterInt64.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Int64] {
        let len: Int32 = try readInt(&buf)
        var seq = [Int64]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterInt64.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiChatItem: FfiConverterRustBuffer {
    typealias SwiftType = [FfiChatItem]

    public static func write(_ value: [FfiChatItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiChatItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiChatItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiChatItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiChatItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiMessage: FfiConverterRustBuffer {
    typealias SwiftType = [FfiMessage]

    public static func write(_ value: [FfiMessage], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiMessage] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiMessage]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiMessage.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_zeromax_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_add_reaction() != 35548) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_change_profile() != 29684) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_check_2fa_password() != 53811) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_complete_qr_login() != 3359) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_connect() != 691) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_connect_for_auth() != 25294) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_delete_message() != 23852) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_edit_message() != 29220) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_fetch_history() != 23702) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_get_chat_list() != 43668) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_get_me() != 4689) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_get_user() != 63722) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_is_connected() != 63715) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_join_chat() != 352) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_leave_chat() != 60318) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_load_all_chats() != 43267) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_login_with_code() != 27488) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_poll_qr_status() != 33346) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_read_message() != 46752) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_remove_reaction() != 42481) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_request_code() != 33977) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_request_qr() != 32989) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_resolve_dialog_users() != 37157) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_send_message() != 2906) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_send_typing() != 20806) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_server_logout() != 56870) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_set_event_listener() != 215) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_set_token() != 64135) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_start_background_reconnect() != 11006) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_start_event_loop() != 53326) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_sync_after_login() != 35491) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_zeromaxclient_verify_code() != 30443) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_constructor_zeromaxclient_new_client() != 2554) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_eventlistener_on_new_message() != 62548) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_eventlistener_on_message_edited() != 31155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_eventlistener_on_message_deleted() != 40523) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_eventlistener_on_chat_updated() != 47641) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeromax_ffi_checksum_method_eventlistener_on_typing() != 9391) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitEventListener()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all