use serde_repr::{Deserialize_repr, Serialize_repr};

/// All known protocol opcodes.
///
/// Mapped 1:1 from `pymax/static/enum.py` `Opcode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize_repr, Deserialize_repr)]
#[repr(u16)]
pub enum Opcode {
    Ping = 1,
    Debug = 2,
    Reconnect = 3,
    Log = 5,
    SessionInit = 6,
    Profile = 16,
    AuthRequest = 17,
    Auth = 18,
    Login = 19,
    Logout = 20,
    Sync = 21,
    Config = 22,
    AuthConfirm = 23,
    PresetAvatars = 25,
    AssetsGet = 26,
    AssetsUpdate = 27,
    AssetsGetByIds = 28,
    AssetsAdd = 29,
    SearchFeedback = 31,
    ContactInfo = 32,
    ContactAdd = 33,
    ContactUpdate = 34,
    ContactPresence = 35,
    ContactList = 36,
    ContactSearch = 37,
    ContactMutual = 38,
    ContactPhotos = 39,
    ContactSort = 40,
    ContactVerify = 42,
    RemoveContactPhoto = 43,
    ContactInfoByPhone = 46,
    ChatInfo = 48,
    ChatHistory = 49,
    ChatMark = 50,
    ChatMedia = 51,
    ChatDelete = 52,
    ChatsList = 53,
    ChatClear = 54,
    ChatUpdate = 55,
    ChatCheckLink = 56,
    ChatJoin = 57,
    ChatLeave = 58,
    ChatMembers = 59,
    PublicSearch = 60,
    ChatClose = 61,
    ChatCreate = 63,
    MsgSend = 64,
    MsgTyping = 65,
    MsgDelete = 66,
    MsgEdit = 67,
    ChatSearch = 68,
    MsgSharePreview = 70,
    MsgGet = 71,
    MsgSearchTouch = 72,
    MsgSearch = 73,
    MsgGetStat = 74,
    ChatSubscribe = 75,
    VideoChatStart = 76,
    ChatMembersUpdate = 77,
    VideoChatHistory = 79,
    PhotoUpload = 80,
    StickerUpload = 81,
    VideoUpload = 82,
    VideoPlay = 83,
    ChatPinSetVisibility = 86,
    FileUpload = 87,
    FileDownload = 88,
    LinkInfo = 89,
    MsgDeleteRange = 92,
    SessionsInfo = 96,
    SessionsClose = 97,
    PhoneBindRequest = 98,
    PhoneBindConfirm = 99,
    ConfirmPresent = 101,
    GetInboundCalls = 103,
    ExternalCallback = 105,
    AuthValidatePassword = 107,
    AuthValidateHint = 108,
    AuthVerifyEmail = 109,
    AuthCheckEmail = 110,
    AuthSet2fa = 111,
    AuthCreateTrack = 112,
    AuthLoginCheckPassword = 115,
    ChatComplain = 117,
    MsgSendCallback = 118,
    SuspendBot = 119,
    LocationStop = 124,
    LocationSend = 125,
    LocationRequest = 126,
    GetLastMentions = 127,
    NotifMessage = 128,
    NotifTyping = 129,
    NotifMark = 130,
    NotifContact = 131,
    NotifPresence = 132,
    NotifConfig = 134,
    NotifChat = 135,
    NotifAttach = 136,
    NotifCallStart = 137,
    NotifContactSort = 139,
    NotifMsgDeleteRange = 140,
    NotifMsgDelete = 142,
    NotifCallbackAnswer = 143,
    ChatBotCommands = 144,
    BotInfo = 145,
    NotifLocation = 147,
    NotifLocationRequest = 148,
    NotifAssetsUpdate = 150,
    NotifDraft = 152,
    NotifDraftDiscard = 153,
    NotifMsgDelayed = 154,
    NotifMsgReactionsChanged = 155,
    NotifMsgYouReacted = 156,
    CallsToken = 158,
    NotifProfile = 159,
    WebAppInitData = 160,
    DraftSave = 176,
    DraftDiscard = 177,
    MsgReaction = 178,
    MsgCancelReaction = 179,
    MsgGetReactions = 180,
    MsgGetDetailedReactions = 181,
    StickerCreate = 193,
    StickerSuggest = 194,
    VideoChatMembers = 195,
    ChatHide = 196,
    ChatSearchCommonParticipants = 198,
    ProfileDelete = 199,
    ProfileDeleteTime = 200,
    AssetsRemove = 259,
    AssetsMove = 260,
    AssetsListModify = 261,
    FoldersGet = 272,
    FoldersGetById = 273,
    FoldersUpdate = 274,
    FoldersReorder = 275,
    FoldersDelete = 276,
    NotifFolders = 277,
    GetQr = 288,
    GetQrStatus = 289,
    LoginByQr = 291,
}

impl Opcode {
    /// Whether this opcode is a server-push notification.
    pub fn is_notification(self) -> bool {
        let v = self as u16;
        (128..=160).contains(&v) || v == 277
    }
}

impl std::fmt::Display for Opcode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}({})", self, *self as u16)
    }
}
